apiVersion: v1
kind: ServiceAccount
metadata:
  name: crossmind-api
  namespace: crossmind
  labels:
    app.kubernetes.io/name: crossmind
    app.kubernetes.io/component: api
automountServiceAccountToken: false
